# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CETACApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CETACApp
pod 'Firebase/Firestore'

# Optionally, include the Swift extensions if you're using Swift.
pod 'FirebaseFirestoreSwift'
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Charts'

target 'CETACAppTests' do
inherit! :search_paths
end

end